# Generated by Django 5.0.6 on 2026-04-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='topics',
            field=models.ManyToManyField(blank=True, to='accountDetails.topic'),
        ),
    ]
