# Generated by Django 5.0.6 on 2026-04-15 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountDetails', '0002_module_topics'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.student'),
        ),
    ]
