# Generated by Django 5.0.6 on 2026-02-03 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accountDetails', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModuleMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mark2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountDetails.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
